[animation]
current = "down"

[animation.sets.down]
delay = -1
start = 0
end = 1

[animation.sets.right]
delay = -1
start = 1
end = 2

[animation.sets.left]
delay = -1
start = 2
end = 3

[animation.sets.up]
delay = -1
start = 3
end = 4

[collision]
size = [16, 16]

[event]
listen = ["COLLISION"]

[script]
path = "arrow_script"

[sprite]
parent = "arrow"

[tag]
tags = ["arrow", "weapon"]

[transform]
scale = [2, 2]
layer = 10