[animation]
current = "idle_down"

[animation.sets.idle_down]
delay = -1
start = 0
end = 1

[animation.sets.idle_right]
delay = -1
start = 1
end = 2

[animation.sets.idle_left]
delay = -1
start = 2
end = 3

[animation.sets.idle_up]
delay = -1
start = 3
end = 4

[animation.sets.walk_down]
delay = 0.07
start = 4
end = 12

[animation.sets.walk_right]
delay = 0.07
start = 12
end = 20

[animation.sets.walk_left]
delay = 0.07
start = 20
end = 28

[animation.sets.walk_up]
delay = 0.07
start = 28
end = 36

[animation.sets.sword_down]
delay = 0.05
start = 36
end = 42

[animation.sets.sword_right]
delay = 0.05
start = 44
end = 48

[animation.sets.sword_left]
delay = 0.05
start = 52
end = 56

[animation.sets.sword_up]
delay = 0.05
start = 60
end = 66

[collision]
size = [16, 16]
solid = true
persistent = true

[event]
listen = ["PLAYER", "PYGAME"]

[script]
path = "player_script"
args = [0]

[sprite]
parent = "player"
offset = [4, 10]

[tag]
tags = ["player"]

[transform]
scale = [2, 2]
layer = 10